[mcp_servers.github]
args = [
    "-y",
    "@modelcontextprotocol/server-github",
]
command = "npx"

[mcp_servers.github.env]
GITHUB_PERSONAL_ACCESS_TOKEN = "PASTE_GITHUB_TOKEN_HERE"

[mcp_servers.supabase]
url = "https://mcp.supabase.com/mcp"

[mcp_servers.vercel]
url = "https://mcp.vercel.com"

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
SUPABASE_PROJECT_ID = "fwnkyhlffjzobegjyodk"
